module.exports = {
  JOIN_ROOM_ERROR: 'JOIN_ROOM_ERROR',
  OUT_JOIN_ROOM: 'OUT_JOIN_ROOM',
  UPDATE_PLAYER_LIST: 'UPDATE_PLAYER_LIST',
  OUT_LEAVE_ROOM: 'OUT_LEAVE_ROOM',
  OUT_START_GAME: 'OUT_START_GAME',
  START_GAME: 'START_GAME',
  UPDATE_ROLE: 'UPDATE_ROLE',
  OUT_GET_PIECES: 'OUT_GET_PIECES',
  GET_PIECES: 'GET_PIECES',
  BLOCK_ROW: 'BLOCK_ROW',
  OUT_BLOCK_ROW: 'OUT_BLOCK_ROW',
  OUT_CHANGE_MAP: 'OUT_CHANGE_MAP',
};
