module.exports = {
  JOIN_ROOM_ERROR: 'JOIN_ROOM_ERROR',
  OUT_JOIN_ROOM: 'OUT_JOIN_ROOM',
  UPDATE_PLAYER_LIST: 'UPDATE_PLAYER_LIST',
  OUT_LEAVE_ROOM: 'OUT_LEAVE_ROOM',
  OUT_START_GAME: 'OUT_START_GAME',
  START_GAME: 'START_GAME',
};
